import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav className="flex gap-6 p-4 border-b mb-6">
          <Link href="/" className="font-semibold">Home</Link>
          <Link href="/artists" className="font-semibold">Artists</Link>
          <Link href="/artists/onboard" className="font-semibold">Onboard Artist</Link>
          <Link href="/artists/dashboard" className="font-semibold">Dashboard</Link>
        </nav>
        {children}
      </body>
    </html>
  );
}
